version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: nuget restore
build:
  project: EventEngine.sln
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: tWXpKD4y8ggiDkQfyTc8zt4wQS8Fa4khSE9ETmC8Yp6YLOsA2kF2Dpde1F4ZHZYU
  on:
    branch: master
- provider: GitHub
  auth_token:
    secure: Q8uS9Onj7HxkERPJ7IbO3smZsK8JP1SDpDsYlpYM9sasIC7bk3I+UQbiHsnyAhuP
  on:
    branch: master